<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- REPORT GENERATOR -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),SC*,EX*,ID*,PL*,SN*,SQ*,UF*,USE*,BT*,BTI*,NT*,NTI*,RT*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT SC (#PCDATA)>
<!ELEMENT EX (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT PL (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT SQ (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT BTI (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT NTI (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>Academic Library</DESCRIPTOR>
 <SC>CH Sales Channel</SC><!-- unknown line type [@@@] -->

 <ID>academic_library</ID>
 <PL>Academic Library</PL>
 <SN>A library associated with an institution of Higher Education supporting post-graduate studies.</SN>
 <BT>Library</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Academic Publishing</DESCRIPTOR>
 <SC>SECT Publishing Sector</SC><!-- unknown line type [@@@] -->

 <ID>academic_publishing</ID>
 <PL>Academic</PL>
 <SN>That sector of publishing focused on publishing material, generally monographs, of interest to academics. This sector is primarly, though not exclusively, the domain of University Presses.</SN>
 <UF>Scholarly Publishing</UF>
 <UF>University presses</UF>
 <BT>Book publishing [Sector]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accounts Payable [Function]</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>accounts_payable_function</ID>
 <BT>Finance [Function]</BT>
 <RT>Accounts payable [Liability]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accounts payable [Liability]</DESCRIPTOR>
 <ID>accounts_payable_liability</ID>
 <BT>Current liabilities</BT>
 <RT>Accounts Payable [Function]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accounts Receivable [Asset]</DESCRIPTOR>
 <ID>accounts_receivable_asset</ID>
 <BT>Current assets</BT>
 <RT>Accounts Receivable [Function]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accounts Receivable [Function]</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>accounts_receivable_function</ID>
 <SN>The management of invoices that have been cut, but for which the cash has not yet been received.AR consists of a number of activities including collections, cash application, credit and debit reconciliation.</SN>
 <BT>Finance [Function]</BT>
 <RT>Accounts Receivable [Asset]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accumulated depreciation</DESCRIPTOR>
 <ID>accumulated_depreciation</ID>
 <BT>Fixed Assets</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acquisition</DESCRIPTOR>
 <SC>FN Publishing Function</SC><!-- unknown line type [@@@] -->

 <ID>acquisition_function</ID>
 <PL>Acquisition</PL>
 <SN>Identification of a concept or manuscript suitable for publication through completed contract with authors or sources. &quot;Acquisition&quot; in this context generally refers to acquiring the rights to publish the material.</SN>
 <SQ>10</SQ>
 <BT>Editorial [Function]</BT>
 <NT>Auction</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Adhesive Binding</DESCRIPTOR>
 <SC>SPEC Physical Book Component</SC>
 <ID>adhesive_binding</ID>
 <BT>Binding [Spec]</BT>
 <NT>Burst binding</NT>
 <NT>Notch Binding</NT>
 <NT>Perfect binding</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Adoption process</DESCRIPTOR>
 <ID>adoption_process</ID>
 <BT>Sales [Function]</BT>
 <RT>Higher Education Publishing</RT>
 <RT>K12 Publishing</RT>
 <RT>School</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Adult Trade</DESCRIPTOR>
 <SC>SECT Publishing Sector</SC><!-- unknown line type [@@@] -->

 <ID>adult_trade_publishing</ID>
 <PL>Adult</PL>
 <SN>That sector of publishing focused primarily on providing content for adult consumers across fiction and non-fiction categories.</SN>
 <BT>Trade Publishing</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advance Dating</DESCRIPTOR>
 <ID>advance_dating</ID>
 <BT>Terms of Sale</BT>
 <RT>College bookstore</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advance orders</DESCRIPTOR>
 <ID>advance_orders</ID>
 <BT>Customer order</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advance reader copy</DESCRIPTOR>
 <ID>advance_reader_copy</ID>
 <BT>Lifecycle</BT>
 <BT>Paperback</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advance Shipping Notice</DESCRIPTOR>
 <ID>advance_shipping_notice</ID>
 <BT>Publishing transactions</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advanced Placement</DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>advanced_placement</ID>
 <BT>Secondary School</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advertising</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>advertising</ID>
 <BT>Marketing</BT>
 <NT>Cooperative Advertising</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advertising Model</DESCRIPTOR>
 <ID>advertising_model</ID>
 <BT>Business Models</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Agent</NON-DESCRIPTOR>
 <ID>agent</ID>
 <USE>Literary Agent</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Allocations</DESCRIPTOR>
 <ID>allocations</ID>
 <BT>Selling, General &amp; Administrative</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Alternative Publishing Configurations</DESCRIPTOR>
 <ID>alternative_publishing_configurations</ID>
 <PL>Alternative Publishing Configurations</PL>
 <SN>Alternative ways of organizing the key functions of a publishing enterprise.</SN>
 <SQ>70</SQ>
 <NT>Custom Publishing</NT>
 <NT>Digital Asset Distributor</NT>
 <NT>Offshoring</NT>
 <NT>Packaging</NT>
 <NT>POD</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Amortization</DESCRIPTOR>
 <ID>amortization</ID>
 <BT>Selling, General &amp; Administrative</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Anchor</DESCRIPTOR>
 <ID>Anchor</ID>
 <PL>Anchor</PL>
 <SN>The location in the text to which a note refers, generally indicated in print by a symbol or number in a superscript. In HTML an anchor is generally indicated by an underline or blue text color and signifies the starting point of a link.</SN>
 <BT>Note</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Animation</DESCRIPTOR>
 <ID>Animation</ID>
 <PL>Animation</PL>
 <SN>Media in which the illution of motion is produced by the rapid sequential display of images.</SN>
 <BT>Video</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ANSI X12</DESCRIPTOR>
 <ID>ANSI_X12</ID>
 <PL>ANSI X12</PL>
 <SN>A set of Electronic Data Interchange (EDI) standards from the American National Standards Institute (ANSI). They are now known as ASC X12.</SN>
 <BT>Electronic Data Interchange</BT>
 <BT>Industry Standards</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Anthology</DESCRIPTOR>
 <ID>Anthology</ID>
 <PL>Anthology</PL>
 <SN>A collection of stories, usually on a common theme.</SN>
 <BT>Literary genre</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Application [Platform]</DESCRIPTOR>
 <ID>application_platform</ID>
 <PL>Application</PL>
 <SN>The software used on a computer or other platform to perform a particular function.</SN>
 <BT>Platform</BT>
 <NT>Browser</NT>
 <NT>eBook Software</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Architecture</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>Architecture</ID>
 <PL>Architecture</PL>
 <SN>That enterprise technology function that specifies the standards for enterprise systems including operating systems, hardware, databases and information structures.</SN>
 <BT>Technology [Function]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Art &amp; Design [Function]</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>art_design_function</ID>
 <PL>Art &amp; Design</PL>
 <SN>The determination of the layout and typography of both the interior and cover of a book.</SN>
 <SQ>30</SQ>
 <BT>Print production</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Art program</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>Art_program</ID>
 <PL>Art program</PL>
 <SN>The collection of images that will be used in a particular title. The art program will often be found as a list or series of images at the back of a manuscript.</SN>
 <BT>Book [Content Structure]</BT>
 <NT>Image</NT>
 <RT>Manuscript</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Art Rendering</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>art_rendering_function</ID>
 <PL>Art Rendering</PL>
 <SN>The transformation of rough sketches or image specifications into art that is production ready.</SN>
 <SQ>31</SQ>
 <BT>Print production</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Assessment</DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>Assessment</ID>
 <PL>Assessment</PL>
 <SN>Evaluation of a student&apos;s competence in a body of material. Assessment ranges from low-stakes assessment such as self-tests all the way up to high-stakes assessment in which the student is graded.</SN>
 <BT>Educational Content</BT>
 <NT>Diagnostic Assessment</NT>
 <NT>Formative assessment</NT>
 <NT>Summative assessment</NT>
 <RT>Educational Publishing</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Asset improvement</DESCRIPTOR>
 <ID>asset_improvement</ID>
 <PL>Asset Improvement</PL>
 <SN>Projects to improve the efficiency of corporate assets. These would include advances, inventory and accounts receivable and be reflected in a reduction in the balance sheet assets to support a given level of sales.</SN>
 <BT>Consulting</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Assets</DESCRIPTOR>
 <ID>Assets</ID>
 <PL>Assets</PL>
 <SN>The balance sheet value of everything a company owns or is due to it.  For publishers the primary assets are receivables, inventory and royalty advances.</SN>
 <BT>Balance sheet</BT>
 <NT>Current assets</NT>
 <NT>Fixed Assets</NT>
 <NT>Plant Costs</NT>
 <NT>Royalty advances &amp; guarantees</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Auction</DESCRIPTOR>
 <ID>Auction</ID>
 <PL>Auction</PL>
 <SN>A process by which a literary agent or manager solicits bids from publishers for publishing rights to a property.</SN>
 <BT>Acquisition</BT>
 <RT>Literary Agent</RT>
 <RT>Rights</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Audio [Rights]</DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>audio_rights</ID>
 <PL>Audio rights</PL>
 <SN>The rights to publish books and content in audio formats.</SN>
 <BT>Subsidiary Rights [Rights]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Audio cassette</DESCRIPTOR>
 <ID>audio_cassette</ID>
 <SN>The primary audio recording and distribution format prior to the compact disk.  An audio cassette contains two small reels of magnetic tape enclosed inside a plastic shell.</SN>
 <BT>Media [Audio]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Audio content</DESCRIPTOR>
 <ID>audio_content</ID>
 <PL>Audio content</PL>
 <SN>Content that is consumed aurally, by listening to it.</SN>
 <BT>Multimedia</BT>
 <NT>Music</NT>
 <NT>Sound effects</NT>
 <NT>Voice</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Audio Production</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>audio_production</ID>
 <PL>Audio Production</PL>
 <SN>The publishing functions used to produce audio books and spoken materials.</SN>
 <SQ>40</SQ>
 <BT>Production</BT>
 <NT>Casting</NT>
 <NT>Mastering</NT>
 <NT>Narration</NT>
 <NT>Performing</NT>
 <NT>Scoring</NT>
 <NT>Script Writing</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Audiovisual materials</NON-DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>audiovisual_materials</ID>
 <USE>Multimedia</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Author</DESCRIPTOR>
 <ID>author</ID>
 <PL>Author</PL>
 <SN>The writer of a book or other literary work.</SN>
 <BT>Contributor</BT>
 <RT>Author biography</RT>
 <RT>Author contract</RT>
 <RT>Author image</RT>
 <RT>Contract Management</RT>
 <RT>Publicity</RT>
 <RT>Royalty advances &amp; guarantees</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Author biography</DESCRIPTOR>
 <ID>author_biography</ID>
 <PL>Author biography</PL>
 <SN>The biographical sketch of the author of a work that is generally contained somewhere on the book jacket or cover, or web site devoted to the title.</SN>
 <BT>Book metadata</BT>
 <RT>Author</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Author contract</DESCRIPTOR>
 <ID>author_contract</ID>
 <PL>Author contract</PL>
 <SN>The contract between an author and a publisher that lays out the conditions under which a work will be published.</SN>
 <BT>Contract</BT>
 <RT>Author</RT>
 <RT>Book Publisher</RT>
 <RT>Rights</RT>
 <RT>Royalty advances &amp; guarantees</RT>
 <RT>Royalty expense</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Author image</DESCRIPTOR>
 <ID>author_image</ID>
 <PL>Author image</PL>
 <SN>The photograph of the author of a work that is generally contained somewhere on the book jacket or cover, or web site devoted to the title.</SN>
 <BT>Book metadata</BT>
 <RT>Author</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Author name</DESCRIPTOR>
 <ID>author_name</ID>
 <PL>Author name</PL>
 <SN>The name of the author of a work contained in the book metadata and printed on cover, spine, title page, copyright page and in other places throughout a book and other media.</SN>
 <BT>Book metadata</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Autobiography</DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>autobiography</ID>
 <PL>Autobiography</PL>
 <SN>A biography that is written by the subject of the work.</SN>
 <BT>Literary genre</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Awards</DESCRIPTOR>
 <ID>awards</ID>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Back cover</DESCRIPTOR>
 <ID>Back_cover</ID>
 <PL>Back cover</PL>
 <SN>The back cover of a book. A back cover may be blank, or it may carry promotional or descriptive jacket or other copy intended to be helpful to a potential buyer of the book.</SN>
 <UF>C4</UF>
 <BT>Cover</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Backlist</DESCRIPTOR>
 <ID>backlist</ID>
 <PL>Backlist</PL>
 <SN>Books published in a previous season but still in print and available for sale.</SN>
 <BT>Lifecycle</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Backmatter</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>Backmatter</ID>
 <PL>Back Matter</PL>
 <SN>That part of the text of a book that follows the last page of the last chapter.</SN>
 <BT>Book [Content Structure]</BT>
 <NT>Bibliography</NT>
 <NT>Colophon [Typography]</NT>
 <NT>Endnote</NT>
 <NT>Glossary</NT>
 <NT>Index [Book]</NT>
 <NT>Reference list</NT>
 <RT>Pagination guide</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Backorder</DESCRIPTOR>
 <ID>backorder</ID>
 <PL>Backorder</PL>
 <SN>An item or line on a customer order that cannot ship due to inventory being out of stock, but which would otherwise ship. This is distinct from a future order which has inventory availability, but is being held for other reasons.</SN>
 <BT>Customer order</BT>
 <RT>Future order</RT>
 <RT>Order processing</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Balance sheet</DESCRIPTOR>
 <ID>balance_sheet</ID>
 <PL>Balance sheet</PL>
 <SN>That financial statement on which the assets, liabilities and equity of a company are recorded.</SN>
 <BT>Financial Statement</BT>
 <NT>Assets</NT>
 <NT>Equity</NT>
 <NT>Liabilities</NT>
 <NT>Working Capital</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Basis weight</DESCRIPTOR>
 <ID>Basis_weight</ID>
 <SN>The amount of pulp content contained in a sheet.  Basis weight is measured in pounds in Imperial systems and grams per square meter or gsm in metric systems.</SN>
 <BT>Paper grade</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Benefits</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>benefits</ID>
 <PL>Benefits</PL>
 <SN>That function of human resources that deals with compensation other than wages, such as health insurance.</SN>
 <BT>Human Resources</BT>
 <BT>Salary-related costs</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Berne Convention</DESCRIPTOR>
 <ID>berne_convention</ID>
 <PL>Berne Convention</PL>
 <SN>An international treaty that defines copyright protection among participating nations.  It was signed in 1886 and updated in 1971.</SN>
 <BT>Copyright</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bibliography</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>bibliography</ID>
 <PL>Bibliography</PL>
 <SN>A list of books, articles, etc. used and/or cited in the compilation of a particular title.</SN>
 <BT>Backmatter</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Binding [Function]</DESCRIPTOR>
 <ID>binding_function</ID>
 <PL>Binding function</PL>
 <SN>That part of the manufacturing of a book in which the pages or signature are bound together.</SN>
 <BT>Manufacturing</BT>
 <RT>Binding [Spec]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Binding [Spec]</DESCRIPTOR>
 <SC>SPEC Physical Book Component</SC>
 <ID>book_binding</ID>
 <PL>Binding</PL>
 <SN>The part of a book or magazine that holds the pages together</SN>
 <BT>Physical book component</BT>
 <NT>Adhesive Binding</NT>
 <NT>Case binding</NT>
 <NT>Mechanical binding</NT>
 <NT>Sewn binding</NT>
 <RT>Binding [Function]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Blade coated freesheet</DESCRIPTOR>
 <ID>blade_coated_freesheet</ID>
 <PL>Blade coated freesheet</PL>
 <SN>Higher quality paper that does not contain groundwood which has been coated by a process that uses a flexible steel blade to smooth and remove the excess coating. This results in a sheet with a higher coat weight and an optimal print surface.</SN>
 <BT>Coated paper</BT>
 <BT>Freesheet</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Blade coated groundwood</DESCRIPTOR>
 <ID>blade_coated_groundwood</ID>
 <PL>Blade coated groundwood</PL>
 <SN>Groundwood paper that is coated by a process uses a flexible steel blade to smooth and remove the excess coating. This results in a sheet with a higher coat weight and an optimal print surface.</SN>
 <BT>Coated paper</BT>
 <BT>Groundwood Paper</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Blurb</DESCRIPTOR>
 <ID>blurb</ID>
 <PL>Blurb</PL>
 <SN>A short summary of a book used for promotion purposes in marketing materials or on the jacket of a book.</SN>
 <BT>Book metadata</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Board books</DESCRIPTOR>
 <ID>board_books</ID>
 <PL>Board books</PL>
 <SN>Small books for very young children with pages of cardboard to resist chewing or tearing.</SN>
 <BT>Children&apos;s Books</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Boards</DESCRIPTOR>
 <SC>SPEC Physical Book Component</SC>
 <ID>Boards</ID>
 <PL>Boards</PL>
 <SN>The material which gives the covers of hardcover books their stiffness. Generally thick cardboard.</SN>
 <BT>Cover</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Body matter</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>Bodymatter</ID>
 <PL>Body Matter</PL>
 <SN>The content of the book, generally consisting of parts, chapters and sections.</SN>
 <BT>Book [Content Structure]</BT>
 <NT>Chapter</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bonus</DESCRIPTOR>
 <ID>bonus</ID>
 <PL>Bonus</PL>
 <SN>Non-wage or salary compensation paid generally once per year upon the attainment of personal or company objectives.</SN>
 <BT>Salary-related costs</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book [Content Structure]</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>book_content_structure</ID>
 <PL>Book Content Structure</PL>
 <SN>The logical structure of a book including frontmatter, chapters, etc. This is opposed to the physical structure of a book which would include such elements as the jacket, binding, text block and signatures.</SN>
 <SQ>35</SQ>
 <NT>Art program</NT>
 <NT>Backmatter</NT>
 <NT>Body matter</NT>
 <NT>Book metadata</NT>
 <NT>Cover copy</NT>
 <NT>Flap copy</NT>
 <NT>Frontmatter</NT>
 <NT>Jacket copy</NT>
 <NT>Page [Logical]</NT>
 <NT>Part</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book [Format]</DESCRIPTOR>
 <ID>book_format</ID>
 <PL>Book format</PL>
 <SN>The physical form in which a book is published.</SN>
 <SQ>30</SQ>
 <NT>Digital Format</NT>
 <NT>Print [Format]</NT>
 <RT>Book [Media]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book [Media]</DESCRIPTOR>
 <ID>book</ID>
 <PL>Book</PL>
 <SN>A written work that is published as bound pages.</SN>
 <BT>Media [Textual]</BT>
 <RT>Book [Format]</RT>
 <RT>Literary genre</RT>
 <RT>One-time delivery</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book club [Channel]</DESCRIPTOR>
 <SC>CH Sales Channel</SC>
 <ID>book_club</ID>
 <PL>Book club</PL>
 <SN>A direct mail marketing organization in which a defined selection of books are sold to members, generally at reduced prices.</SN>
 <BT>Sales Channel</BT>
 <NT>Negative option</NT>
 <NT>Professional Book Clubs</NT>
 <RT>Book club [Rights]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book club [Rights]</DESCRIPTOR>
 <ID>book_club_rights</ID>
 <PL>Book club rights</PL>
 <SN>The rights to publish a book club edition.</SN>
 <BT>Subsidiary Rights [Rights]</BT>
 <RT>Book club [Channel]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book design</DESCRIPTOR>
 <ID>book_design</ID>
 <PL>Book design</PL>
 <SN>The typography and layout of a book that merges the content of the book with the physical structure of the book.</SN>
 <NT>Page layout</NT>
 <NT>Pagination guide</NT>
 <NT>Typography</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book fair</DESCRIPTOR>
 <ID>book_fair</ID>
 <PL>Book fair</PL>
 <SN>A publishing convention in which publishers, agents and bookstores come together to buy and sell rights and see what is available for sale.</SN>
 <BT>Support organizations</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book metadata</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>book_metadata</ID>
 <PL>Book metadata</PL>
 <SN>Information about a book including title, author, ISBN, price, and synopsis.</SN>
 <BT>Book [Content Structure]</BT>
 <NT>Author biography</NT>
 <NT>Author image</NT>
 <NT>Author name</NT>
 <NT>Blurb</NT>
 <NT>Cataloging in Publication data</NT>
 <NT>Cover image</NT>
 <NT>DOI</NT>
 <NT>ISBN</NT>
 <NT>ISBN-13</NT>
 <NT>Title</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book Publisher</DESCRIPTOR>
 <ID>book_publisher</ID>
 <PL>Book publisher</PL>
 <SN>An entity that produces and distributes books for public consumption.</SN>
 <BT>Publisher</BT>
 <BT>Value Chain</BT>
 <NT>Imprint</NT>
 <NT>Small presses</NT>
 <RT>Author contract</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book publishing [Sector]</DESCRIPTOR>
 <SC>SECT Publishing Sector</SC>
 <ID>book_publishing_sector</ID>
 <PL>Book Publishing Sector</PL>
 <SN>The major types of book publishing distinguished by the types of customers and uses to which they put information published.</SN>
 <BT>Media Sector</BT>
 <NT>Academic Publishing</NT>
 <NT>Educational Publishing</NT>
 <NT>Professional Publishing</NT>
 <NT>Reference Publishing</NT>
 <NT>Self-Publishing</NT>
 <NT>Trade Publishing</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Booksellers</NON-DESCRIPTOR>
 <ID>booksellers</ID>
 <USE>Bookstore</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bookstore</DESCRIPTOR>
 <SC>CH Sales Channel</SC>
 <ID>bookstore</ID>
 <PL>Bookstore</PL>
 <SN>A retailer that deals primarily in books.</SN>
 <UF>Booksellers</UF>
 <BT>Retail</BT>
 <BT>Retailer</BT>
 <BT>Value Chain</BT>
 <NT>Chain bookstore</NT>
 <NT>College bookstore</NT>
 <NT>Independent Bookstore</NT>
 <NT>Medical Bookstore</NT>
 <NT>Online bookstore</NT>
 <NT>Religious Bookstore</NT>
 <RT>Cooperative Advertising</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bottom margin</DESCRIPTOR>
 <ID>bottom_margin</ID>
 <PL>Bottom margin</PL>
 <SN>The blank space beneath the text on a page.  Sometimes a page number, or folio, is displayed in the bottom margin.</SN>
 <BT>Margin</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bound galley</DESCRIPTOR>
 <ID>bound_galley</ID>
 <PL>Bound galley</PL>
 <SN>A bound set of early pages sent out by a publisher for marketing purposes.</SN>
 <UF>Uncorrected proofs</UF>
 <BT>Lifecycle</BT>
 <BT>Paperback</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Boxed text</DESCRIPTOR>
 <SC>COMP Logical Book Component</SC>
 <ID>boxed_text</ID>
 <PL>Boxed text</PL>
 <SN>Out of line notes that are inserted into the running text that offer additional information to the body text. Boxed text is set off from the main text typographically through the use of lines creating a box.</SN>
 <BT>Note</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Brightness</DESCRIPTOR>
 <ID>Brightness</ID>
 <BT>Paper grade</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>British Commonwealth [Rights]</DESCRIPTOR>
 <ID>British_Commonwealth</ID>
 <PL>British Commonwealth</PL>
 <SN>A group of nations including the UK and former British colonies that pay allegiance to the British Crown.  These include Canada, Australia, Republic of Ireland, Republic of India, New Zealand, and the Republic of South Africa.</SN>
 <BT>Territory [Rights]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>British Copyright Act of 1710</DESCRIPTOR>
 <ID>copyright_act_1710</ID>
 <PL>Copyright Act of 1710</PL>
 <SN>England&apos;s Statute of Anne (1710) is generally regarded as the first law establishing copyright. It established a public copyright system, established copyright as originating with the author, and established a term for copyright protection.</SN>
 <BT>Copyright</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Broadcast television</DESCRIPTOR>
 <ID>broadcast_television</ID>
 <PL>Broadcast television</PL>
 <SN>Television that is synchronously broadcast via radio waves to household receivers. Broadcast television is characterized by homogeneous program offerings that will appeal to a mass audience.</SN>
 <BT>Media [Visual]</BT>
 <RT>Television [Genre]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Broadsheet</DESCRIPTOR>
 <ID>broadsheet</ID>
 <PL>Broadsheet</PL>
 <SN>The standard, or large-sized newspaper with pages that are double that of a tabloid.  The New York Times is a broadsheet format.</SN>
 <BT>Newspaper [Format]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Browser</DESCRIPTOR>
 <ID>browser</ID>
 <PL>Browser</PL>
 <SN>A software program that is used to interact with information on the World Wide Web.</SN>
 <BT>Application [Platform]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Budgeting</DESCRIPTOR>
 <SC>FN Publishing Function</SC>
 <ID>budgeting</ID>
 <PL>Budgeting</PL>
 <SN>The finance function in which plans for all elements of the financial statements are established and monitored.</SN>
 <BT>Finance [Function]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Burst binding</DESCRIPTOR>
 <ID>burst_binding</ID>
 <PL>Burst binding</PL>
 <SN>A type of adhesive binding in which glue is forced up through slots in each signature during the binding process.</SN>
 <BT>Adhesive Binding</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Business Books</DESCRIPTOR>
 <SC>BT Book Type</SC>
 <ID>business_books</ID>
 <PL>Business books</PL>
 <SN>Books about management, economics, finance and investing, accounting, auditing, tax, HR/training and careers, advertising/marketing/sales, real estate, and small business.</SN>
 <BT>Literary genre</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Business Models</DESCRIPTOR>
 <ID>business_models</ID>
 <PL>Business models</PL>
 <SN>The manner in which a company receives money for products or services.</SN>
 <SQ>60</SQ>
 <NT>Advertising Model</NT>
 <NT>Pay per use model</NT>
 <NT>Purchase model</NT>
 <NT>Subscription Model</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Business Systems</DESCRIPTOR>
 <ID>business_systems</ID>
 <PL>Business systems</PL>
 <SN>Core systems used by a company to support its mission critical applications.  These would include financial systems, sales, order processing, and operations management systems.</SN>
 <BT>Technology</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C1</NON-DESCRIPTOR>
 <ID>C1</ID>
 <USE>Front cover</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C1S</NON-DESCRIPTOR>
 <ID>C1S</ID>
 <USE>Coated paper</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C2</NON-DESCRIPTOR>
 <ID>C2</ID>
 <USE>Inside front cover</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C2S</NON-DESCRIPTOR>
 <ID>C2S</ID>
 <USE>Coated paper</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C3</NON-DESCRIPTOR>
 <ID>C3</ID>
 <USE>Inside back cover</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>C4</NON-DESCRIPTOR>
 <ID>C4</ID>
 <USE>Back cover</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cable television</DESCRIPTOR>
 <ID>cable_television</ID>
 <SN>Television that is synchronously broadcast via cable to household receivers. Cable television is characterized by a large variety of channels carrying programming of different sorts.</SN>
 <BT>Media [Visual]</BT>
 <RT>Television [Genre]</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Caliper</DESCRIPTOR>
 <ID>Caliper</ID>
 <SN>The thickness of a sheet of paper, also measured in pages per inch, or PPI.</SN>
 <UF>PPI</UF>
 <BT>Paper grade</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>CALS</DESCRIPTOR>
 <ID>CALS</ID>
 <PL>CALS</PL>
 <SN>An XML markup model used for tables.</SN>
 <BT>XML</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cameron Belt Press</DESCRIPTOR>
 <ID>cameron_belt_press</ID>
 <SN>A type of belt press that both prints and binds a book as part of the same process. Cameron belt presses result in inexpensive printing, but are not suitable for halftones or linescreens.</SN>
 <BT>Printing Technology</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Card deck</DESCRIPTOR>
 <ID>card_deck</ID>
 <SN>A packet of post card sized advertisements with a common theme that are mailed to consumers.</SN>
 <BT>Direct Mail</BT>
 <BT>Mail Order Publishing</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Case binding</DESCRIPTOR>
 <SC>SPEC Physical Book Component</SC>
 <ID>case_binding</ID>
 <SN>A binding style characterized by a hard cover (case) made from boards or other stiff material.</SN>
 <BT>Binding [Spec]</BT>
 <NT>Library binding</NT>
 <NT>McCain binding</NT>
 <NT>Notch Binding</NT>
 <NT>Side-sewn</NT>
 <NT>Smyth-sewn</NT>
 <RT>Cover</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cash</DESCRIPTOR>
 <ID>cash</ID>
 <SN>Money in bank accounts or other readily accessible form.</SN>
 <BT>Current assets</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cash flow projection</DESCRIPTOR>
 <SC>FIN Financial in Nature</SC>
 <SC>FN Publishing Function</SC>
 <ID>cash_flow_projection</ID>
 <SN>A financial projection of future cash flows as part of business planning.</SN>
 <BT>Finance [Function]</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cash flow statement</DESCRIPTOR>
 <SC>FIN Financial in Nature</SC>
 <ID>cash_flow_statement</ID>
 <SN>One of the three major financial statements used by businesses to monitor their operations.  The cash flow statement profiles all incoming cash streams against outgoing cash streams.</SN>
 <BT>Financial Statement</BT>
</CONCEPT>

<CONCEPT>