=== alexgarciac/TMGSite/PDLsite.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Ken Brooks (Publishing Dimensions) -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Ken Brooks (private) -->
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ENTITY % anchors "a">
<!ENTITY % OEBEntities PUBLIC "+//ISBN 0-9673008-1-9//DTD OEB 1.0 Entities//EN" "oeb1.ent">
%OEBEntities;
<!-- Common attributes used by most elements
  id:       ID unique to the entire document.
  class:    List of classes.
-->
<!ENTITY % commonAtts "id     ID    #IMPLIED
        class   CDATA   #IMPLIED
        xref  IDREF #IMPLIED">
<!ENTITY % lists "bulletList | orderedList | unOrderedList">
<!ENTITY % textElements "#PCDATA | subscript | superscript | bold | italic | smallCaps | underline |  xrefURL | xrefInternal | projectList">
<!ENTITY % imageAtts 'id ID #IMPLIED
	src CDATA #REQUIRED
	alt CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	align (inline|center|left|right) "center"
	float (yes|no) #IMPLIED
	role (logo|coverimage|ornament|authorphoto|map|artwork|photo) #IMPLIED
	orientation CDATA #IMPLIED
	page-break-before (always) #IMPLIED
     page-break-after (always) #IMPLIED
'>
<!ENTITY % paraElements "para | image">
<!ELEMENT activity (#PCDATA)>
<!ELEMENT analysis (analysisName, analysisDescription, analysisActivities?, analysisBenefits?)>
<!ATTLIST analysis
	id ID #REQUIRED
>
<!ELEMENT analysisActivities (activity+)>
<!ELEMENT analysisBenefits (benefit+)>
<!ELEMENT analysisDescription (description+)>
<!ELEMENT analysisName (#PCDATA)>
<!ELEMENT approach (#PCDATA)>
<!ELEMENT benefit (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT clientName (#PCDATA)>
<!ELEMENT projectType (#PCDATA)>
<!ELEMENT document (welcome, services, analysis*, projects, articles, biographies, faq, resources, news)>
<!ELEMENT welcome (para+ | bulletList+ | orderedList+ | unOrderedList+)+>
<!ELEMENT services (masterServiceLine+)>
<!ELEMENT articles (article)+>
<!ELEMENT article (articleHeader | articleTitle | articleSubtitle* | articleDate+ | source+ | subHead+ | para+ | bulletList+ | orderedList+ | unOrderedList+)+>
<!ATTLIST article
	shortName ID #REQUIRED
>
<!ELEMENT articleHeader (DOI+ | articleTitle+ | contributor+ | publisher+ | subject+ | source+ | format+ | category+ | description+ | xrefURL+)+>
<!ELEMENT category (#PCDATA)>
<!ELEMENT articleTitle (#PCDATA)>
<!ELEMENT articleSubtitle (#PCDATA)>
<!ELEMENT articleDate (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT faq (faqentry)+>
<!ELEMENT faqentry (faqquestion+, faqanswer+)>
<!ELEMENT faqquestion (%paraElements;)+>
<!ELEMENT faqanswer (%paraElements;)+>
<!ELEMENT issue (#PCDATA)>
<!ELEMENT masterServiceLine (articleHeader, masterServiceLineName, serviceLineDescription, serviceLinePerspective?, serviceLineIssue?, serviceLine*, serviceLineAnalytics?)>
<!ATTLIST masterServiceLine
	shortName ID #REQUIRED
>
<!ELEMENT masterServiceLineName (#PCDATA)>
<!ELEMENT news (pressRelease)+>
<!ATTLIST pressRelease
	shortName ID #REQUIRED
>
<!ELEMENT pressRelease (articleHeader | pressReleaseTitle | pressReleaseSubtitle* | pressReleaseDate+ | pressReleaseContact+ | Location* | subHead+ | para+ | bulletList+ | orderedList+ | unOrderedList+)+>
<!ELEMENT DOI (#PCDATA)>
<!ELEMENT contributor (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT pressReleaseSubtitle (%textElements;)*>
<!ELEMENT pressReleaseDate (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT pressReleaseContact (company+, name+, title?, phone?, website?, e-mail?)*>
<!ELEMENT company (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT subHead (#PCDATA)>
<!ATTLIST website
	%commonAtts; 
	href CDATA #REQUIRED
>
<!ELEMENT e-mail (#PCDATA)>
<!ATTLIST e-mail
	%commonAtts; 
	href CDATA #REQUIRED
>
<!ELEMENT pressReleaseTitle (%textElements;)*>
<!ELEMENT outcome (#PCDATA)>
<!ELEMENT projects (projectList? | project+)+>
<!ELEMENT project (clientName, projectType, projectDescription)>
<!ATTLIST project
	id ID #IMPLIED
	xref IDREF #REQUIRED
>
<!ELEMENT projectDescription (#PCDATA | description)*>
<!ELEMENT projectList (#PCDATA)>
<!ATTLIST projectList
	ref IDREF #REQUIRED
>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (resourceName | resourceDescription*)+>
<!ATTLIST resource
	href CDATA #REQUIRED
>
<!ELEMENT resourceName (#PCDATA)>
<!ELEMENT resourceDescription (#PCDATA | para)*>
<!ELEMENT serviceLine (serviceLineName, serviceLineDescription, serviceLineIssue?)>
<!ELEMENT serviceLineAnalytics (xrefInternal+)>
<!ELEMENT serviceLineDescription (#PCDATA | para | unOrderedList)*>
<!ELEMENT serviceLineIssue (issue+)>
<!ELEMENT serviceLineName (#PCDATA)>
<!ELEMENT serviceLinePerspective EMPTY>
<!ELEMENT xrefInternal (%textElements;)*>
<!ATTLIST xrefInternal
	xref IDREF #IMPLIED
>
<!ELEMENT biography (name, title, biodescription)>
<!ELEMENT biodescription (#PCDATA)>
<!ELEMENT biographies (biography)+>
<!ATTLIST biographies
	id ID #IMPLIED
>
<!ELEMENT para (%textElements;)*>
<!--  ****************************************************** LIST ******************************************************** -->
<!--
	element: orderedList (apply to HTML <ol / p>) 
	description: numbered list
 -->
<!ELEMENT orderedList (listItem)+>
<!ATTLIST orderedList
	type (alpha | arabic | roman) "arabic"
	case (upper | lower) #IMPLIED
	start CDATA "1"
>
<!--
	element: unOrderedList (apply to HTML <ul / p>) 
	description: un-numbered list
 -->
<!ELEMENT unOrderedList (listItem)+>
<!--
	element: BULLETLIST (apply to HTML <ul / p>) 
	description: bulleted list
 -->
<!ELEMENT bulletList (listItem)+>
<!--
	element:  (apply to HTML <li / p>) 
	description: list item
 -->
<!ELEMENT listItem (%textElements; | %lists;)*>
<!ELEMENT superscript (%textElements; | %anchors;)*>
<!ELEMENT subscript (%textElements; | %anchors;)*>
<!ELEMENT italic (%textElements; | %anchors;)*>
<!ELEMENT bold (%textElements;)*>
<!ELEMENT smallCaps (%textElements;)*>
<!ELEMENT underline (%textElements;)*>
<!-- general elements -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a
	id ID #REQUIRED
>
<!ELEMENT xrefURL (#PCDATA)>
<!ATTLIST xrefURL
	%commonAtts; 
	href CDATA #REQUIRED
>
<!--  ****************************************************** IMAGES ******************************************************** -->
<!-- element: IMAGE -->
<!ELEMENT image (caption)>
<!ELEMENT caption (#PCDATA)>
<!ATTLIST image
	%imageAtts; 
>

=== alexgarciac/TMGSite/PDLwebsite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Ken Brooks (Treadwell Media Group) -->
<!-- <!DOCTYPE document SYSTEM "http://treadwellmedia.org/website/XML/PDLsite.dtd"> -->
<?xml-stylesheet type="text/xsl" href="S:\Treadwell Media Group\TMG Site\PDL2HTML.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S:\Treadwell Media Group\TMG Site\TMG Site.xsd">
	<welcome>
		<para>
			<bold>Innovative Publishing Solutions</bold>: eBooks, consulting, editorial, marketing, distribution...a single solutions source</para>
		<para>Backed by seasoned publishing professionals across the editorial, production and marketing/sales spectrum, TMG provides affordable solutions to publishers at a critical stage of growth by grouping and supporting shared services. We allow our clients to concentrate on crafting their best assets and delivering their core competencies while we provide the rest.</para>
		<para>Services include:</para>
		<bulletList>
			<listItem>Distribution in print and electronic formats specializing in small lists into key markets</listItem>
			<listItem>eBook and other electronic content and graphics development including rich media</listItem>
			<listItem>Packaging, offering a full range of services from concept to disc</listItem>
			<listItem>State of the art production and manufacturing</listItem>
			<listItem>Editorial - from start to finish including content creation, editing, copyediting and proofing</listItem>
			<listItem>Creative design</listItem>
			<listItem>Consulting</listItem>
		</bulletList>
		<para>Whether you are a publisher interested in building value through the addition of digital delivery and eBook formats, an international publisher hoping to establish a foothold in the US market, or a content provider or publisher who needs an experienced packager, TMG is your single source for solutions.</para>
		<para>The founders of TMG have been adding value to publishers and authors in the trade and professional fields for more than a decade, working in both electronic media as well as traditional publishing. Through a creative and consultative approach to solving client needs, and drawing on networks of publishing professionals in the field, they support an enterprise dedicated to achievement and profit for their clients. TMG favors the team approach to solutions, believing that success follows from the interaction of a community of inspired equals.</para>
	</welcome>
	<services>
		<masterServiceLine shortName="marketing">
			<articleHeader>
				<subject>Book marketing, galley, ARC, print on demand, POD, eBook galleys, bound galley</subject>
				<DOI>10.13350000000012</DOI>
			</articleHeader>
			<masterServiceLineName>DigitalGalley Book Marketing Services</masterServiceLineName>
			<serviceLineDescription>
				<para>Treadwell Media Group has built its reputation by offering high-quality content conversion and consulting services to publishers entering the eBook space. Now it offers DigitalGalley, a new program that removes costs from the galley and ARC distribution process while simultaneously adding flexibility to it.</para>
				<para>Publishers have long known that the best way to build distribution and then sell-through for a book is through word-of-mouth initiated by "thought" leaders such as reviewers, librarians, and booksellers. It has always been difficult to reach these thought leaders, not only because of the expense of printing and distributing bound galleys and advance reader's copies, but also because these leaders vary by book type and subject; a source well regarded for his/her business book recommendations can't always recommend the latest thriller.</para>
				<para>Treadwell Media Group has recognized this problem, and with the introduction of our DigitalGalley service, <xrefURL href="http://www.DigitalGalley.com">www.DigitalGalley.com</xrefURL>, we have taken the first step toward addressing it. This service delivers digital copies of forthcoming books in many popular formats—including the most popular—Palm Digital Media (formerly Peanut Press). Naturally, this process can be applied to either a selection from a book or a book in its entirety. With DigitalGalley publishers have a low-cost and fast new channel through which they can reach reviewers, librarians and booksellers. For those yet to adopt the new technology, we also offer traditional bound galley production and distribution services.</para>
				<para>DigitalGalley is the first of an anticipated suite of marketing services to come from Treadwell Media Group. During the months ahead we will continue to add services to make book marketing an increasingly painless but fruitful process for publishers.</para>
				<para>For further information on DigitalGalley or the ways in which Treadwell Media Group can assist you with your book production, distribution and marketing needs, please contact Ken Brooks at kbrooks@treadwellmedia.com.</para>
				<para>Features of DigitalGalley:</para>
				<unOrderedList>
					<listItem>Create your own publisher galley page or use one of ours</listItem>
					<listItem>Create your own title page or use one of ours</listItem>
					<listItem>Secure or "shareable" distribution of eBook content, either as selections or full titles</listItem>
					<listItem>Registration of eBook downloads to know who is looking at which title</listItem>
					<listItem>Direct connection with reviewers allowing them to request printed galleys</listItem>
					<listItem>Access to Treadwell Media Group mailing list of reviewers to enhance your own</listItem>
					<listItem>Printing and distribution of traditional bound galleys and ARCs in conjunction with or in place of eBook distribution</listItem>
					<listItem>Customized book marketing services available on request: let our team of designers and engineers work with you to achieve your book marketing goals</listItem>
				</unOrderedList>
			</serviceLineDescription>
		</masterServiceLine>
		<masterServiceLine shortName="distribution">
			<articleHeader>
				<subject>ebook distribution, book distribution, ebooks, Quiet Island, Treadwell Media Group, Ken Brooks</subject>
				<DOI>10.13350000000011</DOI>
			</articleHeader>
			<masterServiceLineName>Quiet Island Books eBook and POD Distribution Services</masterServiceLineName>
			<serviceLineDescription>
				<para>
					<xrefURL href="http://www.QuietIslandBooks.com">Quiet Island Books</xrefURL> Quiet Island Books assists small publishers and previously published authors by distributing their content through secure eBook and print-on-demand wholesale and retail channels.</para>
				<para>Currently, Treadwell Media Group distributes to most on-line and eBook retailers through:</para>
				<unOrderedList>
					<listItem>
						<xrefURL href="http://www.eReader.com">eReader.com</xrefURL> (formerly Palm Digital Media)
					</listItem>
					<listItem>
						<xrefURL href="http://www.mobipocket.com">Mobipocket</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.contentreserve.com">ContentReserve</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.lightningsource.com">Lightning Source</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.ebooks.com">eBooks.com</xrefURL>
					</listItem>
				</unOrderedList>
				<para>Current members of the Quiet Island Books community include:</para>
				<unOrderedList>
					<listItem>
						<xrefURL href="http://www.10step.com">10 Step Publications</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.advisorworks.com">AdvisorWorks</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.americantri.com">American Tri Magazine</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.AtmaGlobal.com">Atma Global</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.clementeonline.com">Clemente Online</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.jobsandmoms.com">Nancy Collamer</xrefURL>
					</listItem>
					<listItem>Barbara Foster</listItem>
					<listItem>
						<xrefURL href="http://www.idealog.com">Idea Logical Company</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.paraview.com">Paraview Press</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.donpendleton.com">Linda Pendleton</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.roverbooks.com">Rover Books</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.softskull.com">Soft Skull Press</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.stormkingpress.com">Storm King Press</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.firstjob.com">Teen Talk Communications</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.veroben.com">Veroben Solutions</xrefURL>
					</listItem>
					<listItem>
						<xrefURL href="http://www.antelopepress.com">WPR Publishing</xrefURL>
					</listItem>
				</unOrderedList>
				<para>Visit Quiet Island Books online at <xrefURL href="http://www.QuietIsland.com">Quiet Island Books</xrefURL>.</para>
			</serviceLineDescription>
		</masterServiceLine>
		<masterServiceLine shortName="econsulting">
			<articleHeader>
				<subject>ebook consulting, XML, PDF, workflow, digital workflow, digital distribution, ebooks, publishing consulting</subject>
				<DOI>10.13350000000013</DOI>
			</articleHeader>
			<masterServiceLineName>ePublishing Consulting Services</masterServiceLineName>
			<serviceLineDescription>
